# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SignupPage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SignupPage

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

  target 'SignupPageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SignupPageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
